version: "3.3"
services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - .docker/db:/var/lib/mysql
    ports:
      - 3307:3306
  redis:
    image: redis:6.0-alpine
    container_name: redis
    ports:
      - 6380:6379
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    volumes:
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    ports:
      - 8080:80
    links:
      - app
  app:
    build:
      context: .docker
      args:
        groupId: ${DOCKER_GROUP_ID}
        userId: ${DOCKER_USER_ID}
    container_name: app
    volumes:
      - ./:/var/www
    links:
      - db
      - redis
